routes/web.php
<?php

use App\Http\Controllers\PrincipalController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::get('/', [PrincipalController::class, 'principalBaterias'])->name('/');

Route::get('/teoria', [PrincipalController::class, 'teoria'])->name('teoria');

Route::get('/procedimento', [PrincipalController::class, 'procedimento'])->name('procedimento');

Route::get('/medicoes', [PrincipalController::class, 'medicoes'])->name('medicoes');

Route::get('/principal', [PrincipalController::class, 'principal']); 

Route::get('/pagina1', [PrincipalController::class, 'pagina1']);

Route::get('/pagina2', [PrincipalController::class, 'pagina2']);

app/Models/Medicoes.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Medicoes extends Model
{
    use HasFactory;
    public function getResistenciaInternaAttribute(){
        return $this->resistencia_carga * ($this->tensao_sem_carga / $this->tensao_com_carga -1);
        
    }
}
//walmir atualizou as medições.

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/PrincipalController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Medicoes;

class PrincipalController extends Controller
{
    public function principalBaterias(){
        return view('principalBaterias');
    }

    public function teoria(){
        return view('teoria');
    }

    public function procedimento(){
        return view('procedimento');
    }

    public function medicoes(){
        $medicoes = Medicoes::all();
        return view('medicoes',compact('medicoes'));
    }
    
    public function principal(){
        return view('principal');
    }

    public function pagina1(){
        return view('pagina1');
    }

    public function pagina2(){
        return view('pagina2');
    }
}

resources/views/medicoes.blade.php
@extends('templates.base')

@section('conteudo')
    <main>
        <h1>Medições</h1>
        <hr>
        <h2>Valores obtidos:</h2>
        <table class="table table-striped table-bordered" id="tbDados">
            <thead>
                <tr>
                    <th>Pilha/Bateria</th>
                    <th>Tensão nominal (V)</th>
                    <th>Capacidade de corrente (mA.h)</th>
                    <th>Tensão sem carga (V)</th>
                    <th>Tensão com carga (V)</th>
                    <th>Resistência de carga (ohm)</th>
                    <th>Resistência interna (ohm)</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($medicoes as $medicao)
                    <tr>
                        <td>{{$medicao->pilha_bateria}}</td>
                        <td>{{number_format($medicao->tensao_nominal,1,'.','')}}</td>
                        <td>{{$medicao->capacidade_corrente}}</td>
                        <td>{{$medicao->tensao_sem_carga}}</td>
                        <td>{{$medicao->tensao_com_carga}}</td>
                        <td>{{$medicao->resistencia_carga}}</td>
                        <td>{{number_format($medicao->resistencia_interna,3,'.','')}}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
</main>
@endsection

@section('rodape')
    <h4>Rodapé do página medições</h4>
@endsection

resources/views/pagina1.blade.php
@extends('templates.base')

@section('conteudo')
    <h1>Página 1</h1>
    <hr>
@endsection

@section('rodape')
    <h4>Rodapé da página 1</h4>
@endsection

resources/views/pagina2.blade.php
@extends('templates.base')

@section('conteudo')
    <h1>Página 2</h1>
    <hr>
@endsection

@section('rodape')
    <h4>Rodapé da página 2</h4>
@endsection

resources/views/principal.blade.php
@extends('templates.base')

@section('conteudo')
    <h1>Página Principal</h1>
    <hr>
@endsection

@section('rodape')
    <h4>Rodapé da página principal</h4>
@endsection

resources/views/principalBaterias.blade.php
@extends('templates.base')

@section('conteudo')

<main>
    <h1>Turma: 2D1 - Grupo 1</h1>
    <h2>Participantes</h2>
    <hr>
    <table class="table table-striped table-bordered">
    <tr>
        <td>Matricula    </td>
        <td>Nome</td>
        <td>Função</td>
    </tr>
    <tr>
        <td>0072524</td>
        <td>Rayca Lopes</td>
        <td>Gerente</td>
    </tr>
    <tr>
        <td>0072540</td>
        <td>Pedro Ferreira</td>
        <td>Desenvolvedor de Banco de Dados</td>
    </tr>
    <tr>
        <td>0072532</td>
        <td>Tiago Lopes</td>
        <td>Desenvolvedor de Banco de dados</td>
    </tr>
    <tr>
        <td>0072553</td>
        <td>Walmir de Jesus</td>
        <td>Desenvolvedor de CSS</td>
    </tr>
   </table>
</main>

@endsection

@section('rodape')
    <h4>Rodapé da página principal</h4>
@endsection

resources/views/procedimento.blade.php
@extends('templates.base')

@section('conteudo')
    <main>
        <h1>Procedimentos</h1>
        <hr>
        <h2>Primeira etapa: </h2>
        <p>
            ▪️ Com a ajuda de um multimetro medimos a resistêcia do resistor de 22 ohms.
        </p>
        <p>
            ▪️ Depois medimos a tensão de cada pilha e bateria. 
        </p>
        <p>
            ▪️ Em seguida medimos a tensão junto com a corrente do resistor.  
        </p>
        <h3>Segunda etapa: </h3>
        <p>
            ▪️ Escrevemos o código HTML para calcular a resistencia interna de acordo com os valores obtidos.
        </p>
        <p>
            ▪️ Dividimos o codigo em pastas e adicionamos imagens.
        </p>
        <h4>Conclusão: </h4>
        <p>
            ▪️ Concluimos que quando a resistência interna é muito alta, a saúde da pilha não está boa e ela não funciona.
        </p>
        <img src="../imgs/Multímetro.jpg" width="200px">
    </main>
@endsection

@section('rodape')
    <h4>Rodapé do página procedimentos</h4>
@endsection

resources/views/templates/base.blade.php
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>AulaLaravel</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ asset('css/estilos.css')}}">
</head>

<body>
    <div class="container-md">
        <h1>Baterias Laravel</h1>
        <hr>
        <nav>
            <ul>
                <li><a href="{{ route('/') }}">Início</a></li>
                <li><a href="{{ route('teoria') }}">Teoria</a></li>
                <li><a href="{{ route('procedimento') }}">Procedimentos</a></li>
                <li><a href="{{ route('medicoes') }}">Medições</a></li>
            </ul>
        </nav>
        @yield('conteudo')
        <div class= "rodape container-md">
            @yield ("rodape")
        @yield('rodape')
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>

</html>

resources/views/teoria.blade.php
@extends('templates.base')

@section('conteudo')
    <main>
        <h1>Teorias</h1>
        <hr>
        <h2>Descrição das pilhas:</h2>
        <p>
            Pilhas são sistemas eletroquímicos que produzem energia elétrica por meio de reações de oxirredução espontâneas. São classificadas como células galvânicas ou células voltaicas. 
            A energia química se transforma em energia elétrica por meio do fluxo ordenado de elétrons gerados nas reações.
        </p>
        <img src="../imgs/panasonic.jpg" width="150px">

        <p>
            Uma pilha convencional é descartada quando sua carga acaba ou fica em nível insuficiente de energia (fraca). Com uma pilha recarregável, basta utilizar um aparelho adequado para que sua carga de energia seja restabelecida. Com isso, a pilha pode ser utilizada novamente.
        </p>
        <img src="../imgs/uatek.jpg" width="150px">
        <h3>Descrição de baterias:</h3>
        <p>
            As baterias são conjuntos de pilhas ligadas em série, ou seja, são dispositivos eletroquímicos nos quais ocorrem reações de oxidorredução, produzindo uma corrente elétrica. Podem ser chamadas ainda de pilhas secundárias, baterias secundárias ou acumuladores.
        </p>
        <img src="../imgs/golite.jpg" width="150px">
    </main>
    @endsection

@section('rodape')
    <h4>Rodapé da página teoria</h4>
@endsection